version: "3"
services:
  api:
    image: nestjs-api
    ports:
      - "4000-4005:4000"
    expose:
      - "4000"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    ports:
      - "3000:3000"

